models:
  - name: dim_listings_cleansed
    columns:
      - name: listing_id
        data_tests:
          - unique
          - not_null
      - name: listing_name
        data_tests:
          - not_null
      - name: room_type
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Shared room','Hotel room','Private room','Entire home/apt']
      - name: minimum_nights
        data_tests:
          - not_null
      - name: host_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id
      - name: price
        data_tests:
          - not_null
  
  - name: dim_hosts_cleansed
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        data_type: integer
        constraint:
          - type : not_null
          - type: primary_key
      - name: is_superhost
        data_type: string
        constraint:
          - type: check
            expression: "is_superhost IN ('t','f')"
      - name: created_at
        data_type: timestamp
        constraint:
          - type: not_null
      - name: updated_at
        data_type: timestamp
        constraint:
          - type: not_null
      - name: host_name
        data_type: string
        constraint:
          - type: not_null